<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\User;

/**
 * Klasa zawierajaca zapytania do tabeli car orders
 * CarOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarOrderRepository extends EntityRepository
{
    public function getOrdersForUser(User $user){
        return $this->getEntityManager()
            ->createQuery("
                SELECT carOrder, car FROM AppBundle:CarOrder carOrder
                JOIN carOrder.car car
                WHERE carOrder.user= ?1
                ORDER BY carOrder.dateFrom
            ")
            ->setParameter(1, $user->getId())
            ->getResult();
    }
}
