<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function getAllCars() {
        return $this->getEntityManager()
            ->createQuery("SELECT car FROM AppBundle:Car car ORDER BY car.brand, car.model")
            ->getResult()
            ;
    }

    public function getMostPopularCars() {
        return $this->getEntityManager()
            ->createQuery("
                SELECT car, COUNT(car.id) AS HIDDEN cnt FROM AppBundle:Car car
                JOIN car.carOrders carOrder
                GROUP BY car.id
                ORDER BY cnt DESC, car.brand, car.model
            ")
            ->getResult()
            ;
    }

    public function getBestRatedCars() {
        return $this->getEntityManager()
            ->createQuery("
                SELECT car, SUM(carOrder.rate)/COUNT(car.id) AS HIDDEN cnt FROM AppBundle:Car car
                JOIN car.carOrders carOrder
                WHERE carOrder.rate IS NOT NULL
                GROUP BY car.id
                ORDER BY cnt DESC, car.brand, car.model
            ")
            ->getResult()
            ;
    }

    public function getCategories(){
        return $this->getEntityManager()
            ->createQuery("
                SELECT DISTINCT car.category FROM AppBundle:Car car
            ")
            ->getArrayResult();
    }

}
